-- MySQL Script generated by MySQL Workbench
-- Mon Oct  2 04:20:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotel-alura
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotel-alura
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel-alura` DEFAULT CHARACTER SET utf8 ;
USE `hotel-alura` ;

-- -----------------------------------------------------
-- Table `hotel-alura`.`Reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel-alura`.`Reservas` (
  `idReserva` INT NOT NULL AUTO_INCREMENT,
  `fecha_entrada` DATE NULL,
  `fecha_salida` DATE NULL,
  `valor` VARCHAR(45) NULL,
  `formaPago` VARCHAR(45) NULL,
  PRIMARY KEY (`idReserva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel-alura`.`Huespedes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel-alura`.`Huespedes` (
  `idHuesped` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `nacionalidad` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `idReserva` INT NOT NULL,
  PRIMARY KEY (`idHuesped`, `idReserva`),
  INDEX `fk_Huespedes_Reservas_idx` (`idReserva` ASC) VISIBLE,
  CONSTRAINT `fk_Huespedes_Reservas`
    FOREIGN KEY (`idReserva`)
    REFERENCES `hotel-alura`.`Reservas` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

select * from Reservas;
select * from Huespedes;